from glob import glob
import os

# https://stackoverflow.com/questions/60978672/python-string-to-camelcase#60978847
def to_camel_case(text):
    s = text.replace("-", " ").replace("_", " ")
    s = s.split()
    if len(text) == 0:
        return text
    return s[0] + ''.join(i.capitalize() for i in s[1:])

# Expected to run from the root dir
svg = glob(os.path.join(os.getcwd(), "src", "dot", "themes", "icons", "*.svg"))
identity = glob(os.path.join(os.getcwd(), "src", "dot", "themes", "icons", "identity", "*.svg"))
actions = glob(os.path.join(os.getcwd(), "src", "dot", "themes", "icons", "actions", "*.svg"))

icons = svg + identity + actions
icons_ts_path = os.path.join(os.getcwd(), "src", "dot", "core", "icons", "index.ts")

try:
    os.remove(icons_ts_path)
except:
    pass

ic = open(icons_ts_path, "w")
ic.write("""
/* 
    This file was generated by compile-icons.py
    DO NOT EDIT MANUALLY
*/

""")
ic.close()

key = 0
for icon in icons:
    icons[key] = os.path.basename(icon).split(".svg")[0]
    key = key + 1

for icon in sorted(list(dict.fromkeys(icons))):
    name = to_camel_case(icon.capitalize())
    ts_name = f"k{name}Icon"

    with open(icons_ts_path, "a") as f:
        f.write(f'export const {ts_name} = "chrome://dot/content/skin/icons/{icon}.svg";\n')