#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Allows use of mach in dot directory

import os
import sys
 
# Hacky way of getting to topsrcdir
os.chdir("..")

print(f"Executing mach from cwd {os.getcwd()}.")

os.system(" ".join(sys.argv))