#!/bin/sh

build() {
    tsc
}

fix_workspaces() {
    cd firefox
    for file in *; do mv "${file}" "${file/firefox-/}"; done
}

if command -v "node" > /dev/null;
then
    rm .dotbuild/command >/dev/null 2>&1
    echo "$@" >> .dotbuild/command

    case $@ in

    rebuild)
        echo Rebuilding...
        build
    ;;

    fix-workspaces)
        fix_workspaces >/dev/null 2>&1
        echo Updated the workspaces.
    ;;

    *)
        if test -f ".dotbuild/index.js";
        then
            node .dotbuild $@
        else
            yarn
            build
            node .dotbuild $@
        fi
    ;;
    esac
else
    echo "This dot command requires node, which wasn't found on the system!"
    exit 1
fi