#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

run() {
    if command -v "node" > /dev/null;
    then
        if [[ ! -d "$PWD/node_modules" ]]
        then
            if command -v "yarn" > /dev/null;
            then
                yarn
            else
                npm install
            fi
        fi

        node build/index.js $@
        exit $?
    else
        if [ -n "$MOZILLABUILD" ]; then
            PATH="$PATH:/c/Program Files/nodejs"
            node build/index.js $@
        else
            echo "This melon command requires node, which wasn't found on the system!"
            exit 1
        fi
    fi
}

run $@