#!/bin/sh

NODE_HELPER="yarn"

build() {
    if ! command -v yarn &> /dev/null
    then
        NODE_HELPER="npm"
    fi

	$NODE_HELPER run ci-build
}

start_node() {
    if test -f ".dotbuild/index.js";
    then
        node .dotbuild $@
    else
        if ! command -v yarn &> /dev/null
        then
            NODE_HELPER="npm"
            npm i
            build
            node .dotbuild $@
        else
            yarn
            build
            node .dotbuild $@
        fi
    fi
}

run() {
    if command -v "node" > /dev/null;
    then
        mkdir .dotbuild >/dev/null 2>&1
        rm .dotbuild/command >/dev/null 2>&1
        echo "$@" >> .dotbuild/command

        case $@ in
            rebuild)
                echo Rebuilding...
                build
            ;;

            *)
                start_node $@
            ;;
        esac
    else
        if [ -n "$MOZILLABUILD" ]; then
            PATH="$PATH:/c/Program Files/nodejs"
            run $@
        else
            echo "This dot command requires node, which wasn't found on the system!"
            exit 1
        fi
    fi
}

run $@