/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

const icons = [
	"chrome://dot/skin/add.svg",
	"chrome://dot/skin/arrow-down.svg",
	"chrome://dot/skin/arrow-left.svg",
	"chrome://dot/skin/arrow-right.svg",
	"chrome://dot/skin/arrow-up.svg",
	"chrome://dot/skin/briefcase.svg",
	"chrome://dot/skin/brush.svg",
	"chrome://dot/skin/calculator.svg",
	"chrome://dot/skin/camera.svg",
	"chrome://dot/skin/captions.svg",
	"chrome://dot/skin/check.svg",
	"chrome://dot/skin/chevron-down.svg",
	"chrome://dot/skin/chevron-left.svg",
	"chrome://dot/skin/chevron-right.svg",
	"chrome://dot/skin/chevron-up.svg",
	"chrome://dot/skin/clock.svg",
	"chrome://dot/skin/close.svg",
	"chrome://dot/skin/collapse-left.svg",
	"chrome://dot/skin/collapse-right.svg",
	"chrome://dot/skin/cookie.svg",
	"chrome://dot/skin/copy.svg",
	"chrome://dot/skin/cut.svg",
	"chrome://dot/skin/download.svg",
	"chrome://dot/skin/edit.svg",
	"chrome://dot/skin/error.svg",
	"chrome://dot/skin/exit-fullscreen.svg",
	"chrome://dot/skin/folder.svg",
	"chrome://dot/skin/fullscreen.svg",
	"chrome://dot/skin/globe.svg",
	"chrome://dot/skin/heart.svg",
	"chrome://dot/skin/home.svg",
	"chrome://dot/skin/hourglass-filled.svg",
	"chrome://dot/skin/hourglass.svg",
	"chrome://dot/skin/info.svg",
	"chrome://dot/skin/jigsaw.svg",
	"chrome://dot/skin/key.svg",
	"chrome://dot/skin/media-pause.svg",
	"chrome://dot/skin/media-play.svg",
	"chrome://dot/skin/media-stop.svg",
	"chrome://dot/skin/more-horizontal.svg",
	"chrome://dot/skin/more-vertical.svg",
	"chrome://dot/skin/musical-note.svg",
	"chrome://dot/skin/padlock-unsecure.svg",
	"chrome://dot/skin/padlock.svg",
	"chrome://dot/skin/page.svg",
	"chrome://dot/skin/pages.svg",
	"chrome://dot/skin/paste.svg",
	"chrome://dot/skin/picture.svg",
	"chrome://dot/skin/pinpoint.svg",
	"chrome://dot/skin/print.svg",
	"chrome://dot/skin/question.svg",
	"chrome://dot/skin/redo.svg",
	"chrome://dot/skin/reload.svg",
	"chrome://dot/skin/rubbish-bin.svg",
	"chrome://dot/skin/screenshot.svg",
	"chrome://dot/skin/search.svg",
	"chrome://dot/skin/settings.svg",
	"chrome://dot/skin/shield.svg",
	"chrome://dot/skin/shopping-bag.svg",
	"chrome://dot/skin/star.svg",
	"chrome://dot/skin/sync.svg",
	"chrome://dot/skin/toggle.svg",
	"chrome://dot/skin/undo.svg",
	"chrome://dot/skin/user.svg",
	"chrome://dot/skin/warning.svg",
	"chrome://dot/skin/zoom-in.svg",
	"chrome://dot/skin/zoom-out.svg"
];

for (const icon of icons) {
	new Image().src = icon;
}
