
/* 
    This file was generated by compile-icons.py
    DO NOT EDIT MANUALLY
*/

export const kAddIcon = "chrome://dot/content/skin/icons/add.svg";
export const kAudioIcon = "chrome://dot/content/skin/icons/audio.svg";
export const kAudioMutedIcon = "chrome://dot/content/skin/icons/audio-muted.svg";
export const kBackIcon = "chrome://dot/content/skin/icons/back.svg";
export const kBookmarkIcon = "chrome://dot/content/skin/icons/bookmark.svg";
export const kBookmarkFilledIcon = "chrome://dot/content/skin/icons/bookmark-filled.svg";
export const kCalculatorIcon = "chrome://dot/content/skin/icons/calculator.svg";
export const kCertificateIcon = "chrome://dot/content/skin/icons/certificate.svg";
export const kCheckIcon = "chrome://dot/content/skin/icons/check.svg";
export const kChevronDown12Icon = "chrome://dot/content/skin/icons/chevron-down-12.svg";
export const kChevronRight12Icon = "chrome://dot/content/skin/icons/chevron-right-12.svg";
export const kCloseIcon = "chrome://dot/content/skin/icons/close.svg";
export const kCloseTabsIcon = "chrome://dot/content/skin/icons/close-tabs.svg";
export const kCloseTabsToLeftIcon = "chrome://dot/content/skin/icons/close-tabs-to-left.svg";
export const kCloseTabsToRightIcon = "chrome://dot/content/skin/icons/close-tabs-to-right.svg";
export const kCookieIcon = "chrome://dot/content/skin/icons/cookie.svg";
export const kCopyIcon = "chrome://dot/content/skin/icons/copy.svg";
export const kCustomiseIcon = "chrome://dot/content/skin/icons/customise.svg";
export const kCutIcon = "chrome://dot/content/skin/icons/cut.svg";
export const kDefaultFaviconIcon = "chrome://dot/content/skin/icons/default-favicon.svg";
export const kDownloadIcon = "chrome://dot/content/skin/icons/download.svg";
export const kDuplicateTabIcon = "chrome://dot/content/skin/icons/duplicate-tab.svg";
export const kExitFullscreenIcon = "chrome://dot/content/skin/icons/exit-fullscreen.svg";
export const kExtensionIcon = "chrome://dot/content/skin/icons/extension.svg";
export const kFileIcon = "chrome://dot/content/skin/icons/file.svg";
export const kFindInContentIcon = "chrome://dot/content/skin/icons/find-in-content.svg";
export const kForwardIcon = "chrome://dot/content/skin/icons/forward.svg";
export const kFullscreenIcon = "chrome://dot/content/skin/icons/fullscreen.svg";
export const kGestureIcon = "chrome://dot/content/skin/icons/gesture.svg";
export const kHelpIcon = "chrome://dot/content/skin/icons/help.svg";
export const kHistoryIcon = "chrome://dot/content/skin/icons/history.svg";
export const kHomeFilledIcon = "chrome://dot/content/skin/icons/home-filled.svg";
export const kHttpIcon = "chrome://dot/content/skin/icons/http.svg";
export const kHttpsIcon = "chrome://dot/content/skin/icons/https.svg";
export const kHttpsUnsecureIcon = "chrome://dot/content/skin/icons/https-unsecure.svg";
export const kInfoIcon = "chrome://dot/content/skin/icons/info.svg";
export const kInspectIcon = "chrome://dot/content/skin/icons/inspect.svg";
export const kLabIcon = "chrome://dot/content/skin/icons/lab.svg";
export const kLanguageIcon = "chrome://dot/content/skin/icons/language.svg";
export const kMenuIcon = "chrome://dot/content/skin/icons/menu.svg";
export const kMoreIcon = "chrome://dot/content/skin/icons/more.svg";
export const kNavigateIcon = "chrome://dot/content/skin/icons/navigate.svg";
export const kNewBookmarkIcon = "chrome://dot/content/skin/icons/new-bookmark.svg";
export const kNewWindowIcon = "chrome://dot/content/skin/icons/new-window.svg";
export const kNotesIcon = "chrome://dot/content/skin/icons/notes.svg";
export const kPasteIcon = "chrome://dot/content/skin/icons/paste.svg";
export const kPermissionIcon = "chrome://dot/content/skin/icons/permission.svg";
export const kPrintIcon = "chrome://dot/content/skin/icons/print.svg";
export const kRedoIcon = "chrome://dot/content/skin/icons/redo.svg";
export const kReloadIcon = "chrome://dot/content/skin/icons/reload.svg";
export const kRubbishIcon = "chrome://dot/content/skin/icons/rubbish.svg";
export const kScreenshotIcon = "chrome://dot/content/skin/icons/screenshot.svg";
export const kSearchIcon = "chrome://dot/content/skin/icons/search.svg";
export const kSettingsIcon = "chrome://dot/content/skin/icons/settings.svg";
export const kShoppingBagIcon = "chrome://dot/content/skin/icons/shopping-bag.svg";
export const kSpellcheckIcon = "chrome://dot/content/skin/icons/spellcheck.svg";
export const kSyncIcon = "chrome://dot/content/skin/icons/sync.svg";
export const kUndoIcon = "chrome://dot/content/skin/icons/undo.svg";
export const kWarningIcon = "chrome://dot/content/skin/icons/warning.svg";
export const kZoomInIcon = "chrome://dot/content/skin/icons/zoom-in.svg";
export const kZoomOutIcon = "chrome://dot/content/skin/icons/zoom-out.svg";
