name: "Install dependencies" 
description: "Install the required dependencies for the build"
inputs:
  target:
    description: 'Build target'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Sentry SDK
      shell: bash
      run: sudo pip install --upgrade sentry_sdk

    - name: Install apt dependencies
      shell: bash
      run: PYTHONPATH=.github/actions python3 ./.github/actions/dependencies/${{ inputs.target }}.py apt

    - name: Install Rust
      shell: bash
      run: PYTHONPATH=.github/actions python3 ./.github/actions/dependencies/${{ inputs.target }}.py rust

    # We have no pip dependencies yet
    # - name: Install pip dependencies
    #   shell: bash
    #   run: PYTHONPATH=.github/actions python3 ./.github/actions/dependencies/${{ inputs.target }}.py pip

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 
          - "1.53.0"
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: sccache cbindgen